
import { DocsResult, ColorPalette } from "../types";
import PptxGenJS from "pptxgenjs";

// --- Helper: Clean colors ---
const sanitizeColor = (color: string | undefined, defaultColor: string): string => {
  if (!color) return defaultColor;
  return color.replace('#', '');
};

export const exportToDocx = (data: DocsResult) => {
  const header = "<html xmlns:o='urn:schemas-microsoft-com:office:office' " +
        "xmlns:w='urn:schemas-microsoft-com:office:word' " +
        "xmlns='http://www.w3.org/TR/REC-html40'>" +
        "<head><meta charset='utf-8'><title>Export HTML to Word Document with JavaScript</title></head><body>";
  
  const footer = "</body></html>";
  
  // Convert Markdown-ish text to basic HTML for the Word doc
  let htmlBody = data.prd
    .replace(/^### (.*$)/gim, '<h3>$1</h3>')
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    .replace(/^\- (.*$)/gim, '<li>$1</li>')
    .replace(/\*\*(.*)\*\*/gim, '<b>$1</b>')
    .replace(/\n/gim, '<br>');

  const sourceHTML = header + htmlBody + footer;
  
  const blob = new Blob(['\ufeff', sourceHTML], {
    type: 'application/msword'
  });
  
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = 'project_docs.doc'; 
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const exportToPptx = (data: DocsResult, palette?: ColorPalette) => {
  try {
      const pres = new PptxGenJS();
      pres.layout = "LAYOUT_16x9";
      
      // 1. Setup Palette (Modern Dark Default)
      const theme = {
        bg: sanitizeColor(palette?.background, "0F172A"),      // Dark Blue/Slate
        fg: sanitizeColor(palette?.text, "F8FAFC"),            // White/Slate 50
        accent: sanitizeColor(palette?.primary, "6366F1"),     // Primary Brand
        sec: sanitizeColor(palette?.secondary, "A855F7"),      // Secondary Brand
        surf: sanitizeColor(palette?.surface, "1E293B"),       // Surface/Card
        muted: "94A3B8"                                        // Muted Text
      };

      // 2. Define Master Slides (Templates)
      
      // Clean, professional background
      const bgObjects: any[] = [
        { rect: { x: 0, y: 0, w: "100%", h: "100%", fill: { color: theme.bg } } },
        // Subtle geometric accent in top-right corner (Safe area)
        { rect: { x: 9.5, y: 0, w: 0.5, h: 7.5, fill: { color: theme.surf } } },
        { rect: { x: 9.5, y: 0, w: 0.5, h: 1.5, fill: { color: theme.accent } } }
      ];

      // MASTER: TITLE SLIDE
      pres.defineSlideMaster({
        title: "MASTER_TITLE",
        background: { color: theme.bg },
        objects: [
          { rect: { x: 0, y: 0, w: "100%", h: "100%", fill: { color: theme.bg } } },
          // Big accent circle decoration
          { ellipse: { x: 6, y: -2, w: 8, h: 8, fill: { color: theme.accent, transparency: 90 } } },
          { rect: { x: 1, y: 2, w: 1.5, h: 0.1, fill: { color: theme.accent } } }
        ] as any[]
      });

      // MASTER: CONTENT SLIDE
      pres.defineSlideMaster({
        title: "MASTER_CONTENT",
        background: { color: theme.bg },
        objects: [
          ...bgObjects,
          // Footer
          { text: { text: "Generated by AI Architect", options: { x: 0.5, y: 7, w: 4, h: 0.3, fontSize: 9, color: theme.muted } } }
        ] as any[],
        slideNumber: { x: 9.5, y: 7, color: theme.muted, fontSize: 10, align: 'center' }
      });

      // 3. Generate Slides

      // --- SLIDE 1: TITLE ---
      const titleSlide = pres.addSlide({ masterName: "MASTER_TITLE" });
      
      titleSlide.addText(data.slides[0]?.title || "Presentation", {
        x: 1, y: 2.5, w: "80%", h: 2,
        fontSize: 48, color: theme.fg, bold: true, fontFace: "Arial",
        align: 'left', valign: 'top'
      });
      
      titleSlide.addText("PROJECT STRATEGY", {
        x: 1, y: 2.2, w: 5, h: 0.5,
        fontSize: 12, color: theme.accent, bold: true, charSpacing: 4,
        align: 'left'
      });

      // --- CONTENT SLIDES ---
      data.slides.forEach((s) => {
        const slide = pres.addSlide({ masterName: "MASTER_CONTENT" });
        
        // Data cleaning
        const rawContent = s.content || (Array.isArray((s as any).points) ? (s as any).points.join('\n') : '');
        const cleanBullets = rawContent.split('\n')
          .filter(l => l.trim().length > 0)
          .map(l => l.replace(/^[-*•] /, '').trim());

        // Standard Title (Top Left)
        if (s.layout !== 'title') {
            slide.addText(s.title, {
                x: 0.5, y: 0.5, w: "85%", h: 0.8,
                fontSize: 24, color: theme.fg, bold: true, fontFace: "Arial"
            });
        }

        // --- LAYOUT LOGIC ---
        
        if (s.layout === 'title') {
            // Section Break / Impact Slide
            // Dimmed background
            slide.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: '100%', h: '100%', fill: { color: theme.bg, transparency: 10 } });
            
            // Centered Text
            slide.addText(s.title.toUpperCase(), { 
                x: 1, y: 0, w: 8, h: '100%', 
                fontSize: 44, color: theme.accent, align: 'center', bold: true, valign: 'middle' 
            });

        } else if (s.layout === 'split') {
            // Two Columns
            const half = Math.ceil(cleanBullets.length / 2);
            const leftText = cleanBullets.slice(0, half).join('\n\n');
            const rightText = cleanBullets.slice(half).join('\n\n');

            // Left Text
            slide.addText(leftText, {
                x: 0.5, y: 1.5, w: 4.2, h: 5,
                fontSize: 14, color: theme.muted, valign: 'top',
                lineSpacing: 24
            });

            // Right Card Background (Behind text)
            slide.addShape(pres.ShapeType.roundRect, { 
                x: 5.0, y: 1.5, w: 4.2, h: 5, rectRadius: 0.1,
                fill: { color: theme.surf }, 
                line: { color: theme.accent, width: 0, transparency: 80 } 
            });

            // Right Text (On top of card)
            slide.addText(rightText, {
                x: 5.2, y: 1.7, w: 3.8, h: 4.6,
                fontSize: 14, color: theme.fg, valign: 'top',
                lineSpacing: 24
            });

        } else if (s.layout === 'big-number') {
            // Metric Slide
            const mainText = cleanBullets[0] || "100%";
            
            // Dynamic Font Scaling Logic
            let fontSize = 80;
            if (mainText.length > 30) fontSize = 24;
            else if (mainText.length > 20) fontSize = 32;
            else if (mainText.length > 10) fontSize = 48;
            else if (mainText.length > 6) fontSize = 60;

            // Card container centered
            slide.addShape(pres.ShapeType.roundRect, { 
                x: 2.5, y: 2.0, w: 5, h: 3.5, rectRadius: 0.2,
                fill: { color: theme.surf }
            });

            // The Number (with dynamic size)
            slide.addText(mainText, {
                x: 2.5, y: 2.2, w: 5, h: 1.5,
                fontSize: fontSize, color: theme.accent, bold: true, align: 'center',
                autoFit: true 
            });
            
            // The Label
            slide.addText(s.title.toUpperCase(), {
                x: 2.5, y: 4.0, w: 5, h: 1,
                fontSize: 14, color: theme.muted, align: 'center', charSpacing: 2
            });

        } else if (s.layout === 'quote') {
            // Quote Style
            // Decorative bar
            slide.addShape(pres.ShapeType.rect, { x: 1, y: 2, w: 0.1, h: 3, fill: { color: theme.sec } });
            
            slide.addText(`"${rawContent}"`, {
                x: 1.5, y: 2, w: 7.5, h: 3,
                fontSize: 24, color: theme.fg, italic: true, fontFace: "Georgia", valign: 'middle'
            });
            
            slide.addText(`— ${s.title}`, {
                x: 1.5, y: 5.2, w: 7.5, h: 0.5,
                fontSize: 14, color: theme.accent, bold: true
            });

        } else {
            // DEFAULT BULLET LIST
            // Simple, clean list logic
            cleanBullets.forEach((bullet, idx) => {
                const yPos = 1.5 + (idx * 0.7);
                
                // Don't draw off screen
                if (yPos > 6.5) return;

                // Bullet Shape
                slide.addShape(pres.ShapeType.roundRect, {
                    x: 0.5, y: yPos + 0.1, w: 0.15, h: 0.15, rectRadius: 0.05,
                    fill: { color: theme.accent }
                });

                // Bullet Text
                slide.addText(bullet, {
                    x: 0.8, y: yPos, w: 8.5, h: 0.5,
                    fontSize: 16, color: theme.fg, valign: 'top'
                });
            });
        }

        // Speaker Notes
        if (s.speakerNotes) slide.addNotes(s.speakerNotes);
      });

      pres.writeFile({ fileName: `Project_Plan_${data.designStyle || 'modern'}.pptx` });

  } catch (error) {
      console.error("PPTX Generation Error:", error);
      alert("Failed to generate presentation. Please try reloading the page.");
  }
};
